services:
  mongodb:
    image: 'mongo:7'
    ports:
      - '27017:27017'
    volumes:
      - ./recipes.json:/data/recipes.json:ro
      - ./import-data.sh:/docker-entrypoint-initdb.d/import-data.sh:ro
  backend:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
